---
  # Tasks to install and configure PHP 7.1 for WordPress

- name: install php7 and modules
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - php71
    - php71-php-fpm
    - php71-php-gd
    - php71-php-json
    - php71-php-mbstring
    - php71-php-mysqlnd
    - php71-php-pdo
    - php71-php-pecl-apcu
    - php71-php-pecl-apcu-bc
    - php71-php-pecl-igbinary
    - php71-php-pecl-imagick
    - php71-php-pecl-redis # Redis
    - php71-php-xml

- name: Disable default pool
  command: mv /etc/opt/remi/php71/php-fpm.d/www.conf /etc/opt/remi/php71/php-fpm.d/www.disabled
  args:
    creates: /etc/opt/remi/php71/php-fpm.d/www.disabled
  notify: restart php71-php-fpm

- name: Copy redis.ini configuration
  template:
    src: 50-redis.ini
    dest: /etc/opt/remi/php71/php.d/

- name: Copy php71-php-fpm configuration
  template:
    src: wordpress.conf
    dest: /etc/opt/remi/php71/php-fpm.d/

- name: php.ini - Change max upload size to {{ php_upload_max_filesize }}
  replace:
    dest: /etc/opt/remi/php71/php.ini
    regexp: '^upload_max_filesize = .*$'
    replace: 'upload_max_filesize = {{ php_upload_max_filesize }}'

- name: php.ini - Change memory limit to {{ php_memory_limit }}
  replace:
    dest: /etc/opt/remi/php71/php.ini
    regexp: '^memory_limit = .*$'
    replace: 'memory_limit = {{ php_memory_limit }}'

- name: Start php71-php-fpm Service
  service:
    name: php71-php-fpm
    state: started
    enabled: yes
  notify: restart php71-php-fpm
  ignore_errors: true
