---
- name: install php7 and modules
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - php71
    - php71-php-fpm
    - php71-php-gd
    - php71-php-json
    - php71-php-mbstring
    - php71-php-mysqlnd
    - php71-php-pdo
    - php71-php-pecl-apcu
    - php71-php-pecl-apcu-bc
    - php71-php-pecl-igbinary
    - php71-php-pecl-imagick
    - php71-php-pecl-redis # Redis
    - php71-php-xml

- name: Disable default pool
  command: mv /etc/php71-php-fpm.d/www.conf /etc/php71-php-fpm.d/www.disabled creates=/etc/php71-php-fpm.d/www.disabled
  notify: restart php71-php-fpm

- name: Copy php71-php-fpm configuration
  template:
    src: wordpress.conf
    dest: /etc/php71-php-fpm.d/
  notify: restart php71-php-fpm
